# Generated by Django 5.0.4 on 2024-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('tv', 'TV')], max_length=25)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
